name: Github Actions Tutorial

on: [push]

jobs:
  build:
    name: Build and push
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Docker image
        run: docker build -t tutorial-actions .

      - name: Set Tag
        run: docker tag tutorial-actions ${{  secrets.REGISTRY_URL  }}/tutorial-actions:1.0

      - name: Log in to registry
        run: docker login ${{  secrets.REGISTRY_URL  }} -u ${{  secrets.REGISTRY_USERNAME  }} -p ${{  secrets.REGISTRY_PASSWORD  }}

      - name: Push image to registry
        run: docker push ${{  secrets.REGISTRY_URL  }}/tutorial-actions:1.0
